# Creating Training and Testing Datasets

In [1]:
#Relevant Imports
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [2]:
#Read data from csv
data = pd.read_csv("Insurance.csv")
data.head()

age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [3]:
x_data = data.drop(['expenses'], axis=1)
y_data = data['expenses']

In [4]:
#Make training and testing dataset
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3)

In [5]:
#Standardize the dataset
scaler = MinMaxScaler()
x_train_temp = x_train.drop(['sex','smoker','region'], axis=1)
x_test_temp = x_test.drop(['sex','smoker','region'], axis=1)

scaler.fit(x_train_temp)

x_train_temp = pd.DataFrame(data=scaler.transform(x_train_temp), index=x_train_temp.index, columns=x_train_temp.columns)
x_test_temp = pd.DataFrame(data=scaler.transform(x_test_temp), index=x_test_temp.index, columns=x_test_temp.columns)

for col in ['sex','smoker','region']:
    x_train_temp[col] = x_train[col]
    x_test_temp[col] = x_test[col]

x_train = x_train_temp
x_test = x_test_temp

# Create features for tf.estimator

In [6]:
#Create feature columns for the model
#Use numerical column for continous features and buckets for categorical features
age = tf.feature_column.numeric_column("age")
bmi = tf.feature_column.numeric_column("bmi")
child = tf.feature_column.numeric_column("children")
sex = tf.feature_column.categorical_column_with_hash_bucket("sex", hash_bucket_size=10)
smoker = tf.feature_column.categorical_column_with_hash_bucket("smoker", hash_bucket_size=10)
region = tf.feature_column.categorical_column_with_hash_bucket("region", hash_bucket_size=10)

In [7]:
#Put all features into list
feat_cols = [age, bmi, child, sex, smoker, region]

# Linear Regressor Training

In [8]:
#Create input function for training of the model
input_fn = tf.estimator.inputs.pandas_input_fn(x=x_train, y=y_train, batch_size=20, num_epochs=None, shuffle=True)
#Create input function for testing of the model
test_input_fn = tf.estimator.inputs.pandas_input_fn(x=x_test, y=y_test, batch_size=20, num_epochs=1, shuffle=False)

In [9]:
#Declare model
model =tf.estimator.LinearRegressor(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x112a7f8d0>, '_evaluation_master': '', '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_master': '', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_model_dir': '/var/folders/js/vq_cts194qscfxyy3tzq_lg80000gn/T/tmpGSnX3h', '_global_id_in_cluster': 0, '_save_summary_steps': 100}


In [10]:
#Train the model
model.train(input_fn=input_fn, steps=50000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/js/vq_cts194qscfxyy3tzq_lg80000gn/T/tmpGSnX3h/model.ckpt.
INFO:tensorflow:loss = 4551787000.0, step = 1
INFO:tensorflow:global_step/sec: 311.165
INFO:tensorflow:loss = 9848752000.0, step = 101 (0.326 sec)
INFO:tensorflow:global_step/sec: 223.103
INFO:tensorflow:loss = 6022225000.0, step = 201 (0.444 sec)
INFO:tensorflow:global_step/sec: 605.261
INFO:tensorflow:loss = 7072058400.0, step = 301 (0.168 sec)
INFO:tensorflow:global_step/sec: 479.561
INFO:tensorflow:loss = 6766324000.0, step = 401 (0.207 sec)
INFO:tensorflow:global_step/sec: 554.124
INFO:tensorflow:loss = 4886174700.0, step = 501 (0.182 sec)
INFO:tensorflow:global_step/sec: 486.471
INFO:tensorflow:loss = 6915190000.0, step = 601 (0.204

INFO:tensorflow:global_step/sec: 516.275
INFO:tensorflow:loss = 4530525700.0, step = 7801 (0.192 sec)
INFO:tensorflow:global_step/sec: 527.827
INFO:tensorflow:loss = 4996850700.0, step = 7901 (0.190 sec)
INFO:tensorflow:global_step/sec: 463.506
INFO:tensorflow:loss = 5367209000.0, step = 8001 (0.217 sec)
INFO:tensorflow:global_step/sec: 487.714
INFO:tensorflow:loss = 8446049300.0, step = 8101 (0.207 sec)
INFO:tensorflow:global_step/sec: 413.606
INFO:tensorflow:loss = 4540912600.0, step = 8201 (0.241 sec)
INFO:tensorflow:global_step/sec: 405.18
INFO:tensorflow:loss = 6108685300.0, step = 8301 (0.244 sec)
INFO:tensorflow:global_step/sec: 325.733
INFO:tensorflow:loss = 4246549800.0, step = 8401 (0.311 sec)
INFO:tensorflow:global_step/sec: 435.072
INFO:tensorflow:loss = 2886737200.0, step = 8501 (0.226 sec)
INFO:tensorflow:global_step/sec: 546.761
INFO:tensorflow:loss = 3848363300.0, step = 8601 (0.183 sec)
INFO:tensorflow:global_step/sec: 564.87
INFO:tensorflow:loss = 4820250000.0, step =

INFO:tensorflow:global_step/sec: 551.031
INFO:tensorflow:loss = 6288374000.0, step = 15801 (0.183 sec)
INFO:tensorflow:global_step/sec: 560.528
INFO:tensorflow:loss = 4618845000.0, step = 15901 (0.178 sec)
INFO:tensorflow:global_step/sec: 597.779
INFO:tensorflow:loss = 3185168000.0, step = 16001 (0.168 sec)
INFO:tensorflow:global_step/sec: 539.671
INFO:tensorflow:loss = 6356843000.0, step = 16101 (0.184 sec)
INFO:tensorflow:global_step/sec: 554.717
INFO:tensorflow:loss = 5518780000.0, step = 16201 (0.181 sec)
INFO:tensorflow:global_step/sec: 643.497
INFO:tensorflow:loss = 11369616000.0, step = 16301 (0.155 sec)
INFO:tensorflow:global_step/sec: 609.664
INFO:tensorflow:loss = 9296982000.0, step = 16401 (0.167 sec)
INFO:tensorflow:global_step/sec: 567.917
INFO:tensorflow:loss = 3966172700.0, step = 16501 (0.174 sec)
INFO:tensorflow:global_step/sec: 572.679
INFO:tensorflow:loss = 4408312300.0, step = 16601 (0.176 sec)
INFO:tensorflow:global_step/sec: 524.995
INFO:tensorflow:loss = 48426066

INFO:tensorflow:global_step/sec: 425.958
INFO:tensorflow:loss = 3573352200.0, step = 23801 (0.236 sec)
INFO:tensorflow:global_step/sec: 556.659
INFO:tensorflow:loss = 2799307300.0, step = 23901 (0.178 sec)
INFO:tensorflow:global_step/sec: 543.416
INFO:tensorflow:loss = 8691549000.0, step = 24001 (0.184 sec)
INFO:tensorflow:global_step/sec: 470.498
INFO:tensorflow:loss = 2433215200.0, step = 24101 (0.214 sec)
INFO:tensorflow:global_step/sec: 506.675
INFO:tensorflow:loss = 14354551000.0, step = 24201 (0.196 sec)
INFO:tensorflow:global_step/sec: 495.778
INFO:tensorflow:loss = 4259304000.0, step = 24301 (0.203 sec)
INFO:tensorflow:global_step/sec: 545.14
INFO:tensorflow:loss = 5056456700.0, step = 24401 (0.184 sec)
INFO:tensorflow:global_step/sec: 514.841
INFO:tensorflow:loss = 7293675000.0, step = 24501 (0.194 sec)
INFO:tensorflow:global_step/sec: 514.197
INFO:tensorflow:loss = 8681093000.0, step = 24601 (0.197 sec)
INFO:tensorflow:global_step/sec: 533.775
INFO:tensorflow:loss = 425125680

INFO:tensorflow:global_step/sec: 565.061
INFO:tensorflow:loss = 8552278500.0, step = 31801 (0.178 sec)
INFO:tensorflow:global_step/sec: 571.899
INFO:tensorflow:loss = 2692787000.0, step = 31901 (0.176 sec)
INFO:tensorflow:global_step/sec: 539.211
INFO:tensorflow:loss = 3523725300.0, step = 32001 (0.183 sec)
INFO:tensorflow:global_step/sec: 549.451
INFO:tensorflow:loss = 10009742000.0, step = 32101 (0.183 sec)
INFO:tensorflow:global_step/sec: 598.029
INFO:tensorflow:loss = 8498297300.0, step = 32201 (0.167 sec)
INFO:tensorflow:global_step/sec: 622.979
INFO:tensorflow:loss = 6424467000.0, step = 32301 (0.164 sec)
INFO:tensorflow:global_step/sec: 541.064
INFO:tensorflow:loss = 6816142000.0, step = 32401 (0.183 sec)
INFO:tensorflow:global_step/sec: 556.542
INFO:tensorflow:loss = 11072348000.0, step = 32501 (0.178 sec)
INFO:tensorflow:global_step/sec: 556.127
INFO:tensorflow:loss = 4696772600.0, step = 32601 (0.182 sec)
INFO:tensorflow:global_step/sec: 565.08
INFO:tensorflow:loss = 72250235

INFO:tensorflow:global_step/sec: 498.576
INFO:tensorflow:loss = 6663358000.0, step = 39801 (0.203 sec)
INFO:tensorflow:global_step/sec: 364.588
INFO:tensorflow:loss = 8443501600.0, step = 39901 (0.276 sec)
INFO:tensorflow:global_step/sec: 504.62
INFO:tensorflow:loss = 10216753000.0, step = 40001 (0.195 sec)
INFO:tensorflow:global_step/sec: 626.916
INFO:tensorflow:loss = 6518373000.0, step = 40101 (0.161 sec)
INFO:tensorflow:global_step/sec: 587.202
INFO:tensorflow:loss = 4629603300.0, step = 40201 (0.169 sec)
INFO:tensorflow:global_step/sec: 469.883
INFO:tensorflow:loss = 8060218400.0, step = 40301 (0.212 sec)
INFO:tensorflow:global_step/sec: 540.417
INFO:tensorflow:loss = 8680116000.0, step = 40401 (0.185 sec)
INFO:tensorflow:global_step/sec: 553.649
INFO:tensorflow:loss = 4298442000.0, step = 40501 (0.183 sec)
INFO:tensorflow:global_step/sec: 525.569
INFO:tensorflow:loss = 3122989000.0, step = 40601 (0.188 sec)
INFO:tensorflow:global_step/sec: 660.86
INFO:tensorflow:loss = 7240319000

INFO:tensorflow:global_step/sec: 549.1
INFO:tensorflow:loss = 7483083000.0, step = 47801 (0.185 sec)
INFO:tensorflow:global_step/sec: 538.927
INFO:tensorflow:loss = 7823094300.0, step = 47901 (0.185 sec)
INFO:tensorflow:global_step/sec: 554.992
INFO:tensorflow:loss = 7501622300.0, step = 48001 (0.178 sec)
INFO:tensorflow:global_step/sec: 539.34
INFO:tensorflow:loss = 8592876000.0, step = 48101 (0.185 sec)
INFO:tensorflow:global_step/sec: 643.666
INFO:tensorflow:loss = 9236662000.0, step = 48201 (0.157 sec)
INFO:tensorflow:global_step/sec: 535.624
INFO:tensorflow:loss = 3706837200.0, step = 48301 (0.189 sec)
INFO:tensorflow:global_step/sec: 560.281
INFO:tensorflow:loss = 10361166000.0, step = 48401 (0.177 sec)
INFO:tensorflow:global_step/sec: 536.843
INFO:tensorflow:loss = 7154448000.0, step = 48501 (0.184 sec)
INFO:tensorflow:global_step/sec: 580.033
INFO:tensorflow:loss = 5612513300.0, step = 48601 (0.175 sec)
INFO:tensorflow:global_step/sec: 549.505
INFO:tensorflow:loss = 5975826400.

In [11]:
#Evaluate the testing dataset
model.evaluate(input_fn=test_input_fn)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-05-30-19:55:15
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/js/vq_cts194qscfxyy3tzq_lg80000gn/T/tmpGSnX3h/model.ckpt-50000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-05-30-19:55:15
INFO:tensorflow:Saving dict for global step 50000: average_loss = 338788380.0, global_step = 50000, loss = 6485378000.0


{'average_loss': 338788380.0, 'global_step': 50000, 'loss': 6485378000.0}

# Making Predictions

In [12]:
#Create input function for making predictions
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=x_test, batch_size=10, num_epochs=1, shuffle=False)

In [13]:
#Making predictions
predictions = model.predict(input_fn=pred_input_func)

In [14]:
list_predictions = []
for pred in predictions:
    list_predictions.append(pred['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/js/vq_cts194qscfxyy3tzq_lg80000gn/T/tmpGSnX3h/model.ckpt-50000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [15]:
list_predictions

[array([504.84558], dtype=float32),
 array([445.23502], dtype=float32),
 array([448.22867], dtype=float32),
 array([443.70557], dtype=float32),
 array([450.38144], dtype=float32),
 array([405.13168], dtype=float32),
 array([391.08542], dtype=float32),
 array([394.69986], dtype=float32),
 array([418.57], dtype=float32),
 array([403.58728], dtype=float32),
 array([436.84503], dtype=float32),
 array([357.6103], dtype=float32),
 array([451.95218], dtype=float32),
 array([461.60477], dtype=float32),
 array([418.7961], dtype=float32),
 array([402.52078], dtype=float32),
 array([349.82288], dtype=float32),
 array([493.4147], dtype=float32),
 array([401.20676], dtype=float32),
 array([428.94345], dtype=float32),
 array([404.7347], dtype=float32),
 array([473.47784], dtype=float32),
 array([389.99228], dtype=float32),
 array([394.94623], dtype=float32),
 array([455.78458], dtype=float32),
 array([457.6713], dtype=float32),
 array([440.08804], dtype=float32),
 array([447.32285], dtype=float32),


In [16]:
#Calculate error on predictions
error = mean_squared_error(list_predictions, y_test)**0.5

In [17]:
print("Mean Squared Error",error)

('Mean Squared Error', 18406.205091654017)


# DNN Regressor Training

In [18]:
embedded_sex_column = tf.feature_column.embedding_column(sex, dimension=10)
embedded_smoke_column = tf.feature_column.embedding_column(smoker, dimension=10)
embedded_region_column = tf.feature_column.embedding_column(region, dimension=10)

In [19]:
#Put all features into list
feat_cols = [age, bmi, child, embedded_region_column, embedded_sex_column, embedded_smoke_column]

In [20]:
#Create input function for training the model
input_train_func = tf.estimator.inputs.pandas_input_fn(x=x_train, y=y_train, batch_size=10, num_epochs=None, shuffle=True)
#Create input function for testing the model
input_test_func = tf.estimator.inputs.pandas_input_fn(x=x_test, y=y_test, batch_size=10, num_epochs=1, shuffle=False)

In [21]:
#Declare the model
model = tf.estimator.DNNRegressor(hidden_units=[6,6,6], feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x112af7d10>, '_evaluation_master': '', '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_master': '', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_model_dir': '/var/folders/js/vq_cts194qscfxyy3tzq_lg80000gn/T/tmpqgoBs8', '_global_id_in_cluster': 0, '_save_summary_steps': 100}


In [22]:
#Train the model
model.train(input_fn=input_train_func, steps=50000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/js/vq_cts194qscfxyy3tzq_lg80000gn/T/tmpqgoBs8/model.ckpt.
INFO:tensorflow:loss = 2009439700.0, step = 1
INFO:tensorflow:global_step/sec: 215.332
INFO:tensorflow:loss = 2173624000.0, step = 101 (0.467 sec)
INFO:tensorflow:global_step/sec: 368.494
INFO:tensorflow:loss = 427597220.0, step = 201 (0.272 sec)
INFO:tensorflow:global_step/sec: 625.383
INFO:tensorflow:loss = 779849540.0, step = 301 (0.158 sec)
INFO:tensorflow:global_step/sec: 511.483
INFO:tensorflow:loss = 946322200.0, step = 401 (0.197 sec)
INFO:tensorflow:global_step/sec: 546.158
INFO:tensorflow:loss = 356525220.0, step = 501 (0.185 sec)
INFO:tensorflow:global_step/sec: 318.519
INFO:tensorflow:loss = 186729250.0, step = 601 (0.314 sec)

INFO:tensorflow:loss = 778289900.0, step = 7801 (0.178 sec)
INFO:tensorflow:global_step/sec: 545.804
INFO:tensorflow:loss = 575678850.0, step = 7901 (0.184 sec)
INFO:tensorflow:global_step/sec: 550.712
INFO:tensorflow:loss = 300037820.0, step = 8001 (0.182 sec)
INFO:tensorflow:global_step/sec: 530.105
INFO:tensorflow:loss = 793015900.0, step = 8101 (0.187 sec)
INFO:tensorflow:global_step/sec: 514.689
INFO:tensorflow:loss = 376597600.0, step = 8201 (0.195 sec)
INFO:tensorflow:global_step/sec: 545.733
INFO:tensorflow:loss = 257586540.0, step = 8301 (0.183 sec)
INFO:tensorflow:global_step/sec: 510.652
INFO:tensorflow:loss = 118705600.0, step = 8401 (0.194 sec)
INFO:tensorflow:global_step/sec: 556.539
INFO:tensorflow:loss = 352573730.0, step = 8501 (0.180 sec)
INFO:tensorflow:global_step/sec: 540.261
INFO:tensorflow:loss = 273290660.0, step = 8601 (0.186 sec)
INFO:tensorflow:global_step/sec: 681.208
INFO:tensorflow:loss = 356176740.0, step = 8701 (0.146 sec)
INFO:tensorflow:global_step/sec

INFO:tensorflow:global_step/sec: 411.123
INFO:tensorflow:loss = 109076930.0, step = 15901 (0.241 sec)
INFO:tensorflow:global_step/sec: 467.463
INFO:tensorflow:loss = 347640960.0, step = 16001 (0.215 sec)
INFO:tensorflow:global_step/sec: 403.895
INFO:tensorflow:loss = 281862270.0, step = 16101 (0.247 sec)
INFO:tensorflow:global_step/sec: 477.084
INFO:tensorflow:loss = 656145660.0, step = 16201 (0.213 sec)
INFO:tensorflow:global_step/sec: 541.459
INFO:tensorflow:loss = 76596610.0, step = 16301 (0.182 sec)
INFO:tensorflow:global_step/sec: 478.437
INFO:tensorflow:loss = 629669400.0, step = 16401 (0.212 sec)
INFO:tensorflow:global_step/sec: 516.078
INFO:tensorflow:loss = 1455310600.0, step = 16501 (0.191 sec)
INFO:tensorflow:global_step/sec: 474.426
INFO:tensorflow:loss = 224980880.0, step = 16601 (0.212 sec)
INFO:tensorflow:global_step/sec: 506.462
INFO:tensorflow:loss = 488501500.0, step = 16701 (0.201 sec)
INFO:tensorflow:global_step/sec: 487.665
INFO:tensorflow:loss = 522123550.0, step 

INFO:tensorflow:global_step/sec: 583.519
INFO:tensorflow:loss = 311721020.0, step = 24001 (0.173 sec)
INFO:tensorflow:global_step/sec: 536.268
INFO:tensorflow:loss = 231545870.0, step = 24101 (0.189 sec)
INFO:tensorflow:global_step/sec: 514.512
INFO:tensorflow:loss = 125024180.0, step = 24201 (0.195 sec)
INFO:tensorflow:global_step/sec: 500.643
INFO:tensorflow:loss = 296140320.0, step = 24301 (0.196 sec)
INFO:tensorflow:global_step/sec: 565.365
INFO:tensorflow:loss = 446518620.0, step = 24401 (0.177 sec)
INFO:tensorflow:global_step/sec: 622.3
INFO:tensorflow:loss = 116007096.0, step = 24501 (0.162 sec)
INFO:tensorflow:global_step/sec: 548.024
INFO:tensorflow:loss = 270876000.0, step = 24601 (0.179 sec)
INFO:tensorflow:global_step/sec: 523.382
INFO:tensorflow:loss = 158840980.0, step = 24701 (0.193 sec)
INFO:tensorflow:global_step/sec: 557.703
INFO:tensorflow:loss = 463868670.0, step = 24801 (0.179 sec)
INFO:tensorflow:global_step/sec: 629.378
INFO:tensorflow:loss = 203322600.0, step = 

INFO:tensorflow:global_step/sec: 464.574
INFO:tensorflow:loss = 466516670.0, step = 32101 (0.212 sec)
INFO:tensorflow:global_step/sec: 540.325
INFO:tensorflow:loss = 360537380.0, step = 32201 (0.180 sec)
INFO:tensorflow:global_step/sec: 553.305
INFO:tensorflow:loss = 404646560.0, step = 32301 (0.184 sec)
INFO:tensorflow:global_step/sec: 562.287
INFO:tensorflow:loss = 134417330.0, step = 32401 (0.177 sec)
INFO:tensorflow:global_step/sec: 540.806
INFO:tensorflow:loss = 747699840.0, step = 32501 (0.184 sec)
INFO:tensorflow:global_step/sec: 472.228
INFO:tensorflow:loss = 361418800.0, step = 32601 (0.214 sec)
INFO:tensorflow:global_step/sec: 570.324
INFO:tensorflow:loss = 651162560.0, step = 32701 (0.173 sec)
INFO:tensorflow:global_step/sec: 476.526
INFO:tensorflow:loss = 1024835900.0, step = 32801 (0.213 sec)
INFO:tensorflow:global_step/sec: 412.293
INFO:tensorflow:loss = 68648664.0, step = 32901 (0.239 sec)
INFO:tensorflow:global_step/sec: 451.867
INFO:tensorflow:loss = 176317740.0, step 

INFO:tensorflow:global_step/sec: 616.325
INFO:tensorflow:loss = 37771436.0, step = 40201 (0.163 sec)
INFO:tensorflow:global_step/sec: 613.114
INFO:tensorflow:loss = 398749800.0, step = 40301 (0.165 sec)
INFO:tensorflow:global_step/sec: 599.743
INFO:tensorflow:loss = 516275040.0, step = 40401 (0.165 sec)
INFO:tensorflow:global_step/sec: 559.917
INFO:tensorflow:loss = 153133440.0, step = 40501 (0.180 sec)
INFO:tensorflow:global_step/sec: 490.879
INFO:tensorflow:loss = 216466850.0, step = 40601 (0.202 sec)
INFO:tensorflow:global_step/sec: 692.4
INFO:tensorflow:loss = 364502430.0, step = 40701 (0.144 sec)
INFO:tensorflow:global_step/sec: 622.747
INFO:tensorflow:loss = 327202500.0, step = 40801 (0.162 sec)
INFO:tensorflow:global_step/sec: 531.437
INFO:tensorflow:loss = 350503500.0, step = 40901 (0.188 sec)
INFO:tensorflow:global_step/sec: 536.291
INFO:tensorflow:loss = 368475520.0, step = 41001 (0.185 sec)
INFO:tensorflow:global_step/sec: 542.635
INFO:tensorflow:loss = 342645500.0, step = 4

INFO:tensorflow:global_step/sec: 547.861
INFO:tensorflow:loss = 41871170.0, step = 48301 (0.181 sec)
INFO:tensorflow:global_step/sec: 566.871
INFO:tensorflow:loss = 166465180.0, step = 48401 (0.176 sec)
INFO:tensorflow:global_step/sec: 587.914
INFO:tensorflow:loss = 761019970.0, step = 48501 (0.172 sec)
INFO:tensorflow:global_step/sec: 482.341
INFO:tensorflow:loss = 40687600.0, step = 48601 (0.206 sec)
INFO:tensorflow:global_step/sec: 543.47
INFO:tensorflow:loss = 169222160.0, step = 48701 (0.184 sec)
INFO:tensorflow:global_step/sec: 583.863
INFO:tensorflow:loss = 208693950.0, step = 48801 (0.173 sec)
INFO:tensorflow:global_step/sec: 514.967
INFO:tensorflow:loss = 500250100.0, step = 48901 (0.192 sec)
INFO:tensorflow:global_step/sec: 495.246
INFO:tensorflow:loss = 661360000.0, step = 49001 (0.201 sec)
INFO:tensorflow:global_step/sec: 482.295
INFO:tensorflow:loss = 661336770.0, step = 49101 (0.208 sec)
INFO:tensorflow:global_step/sec: 572.764
INFO:tensorflow:loss = 43547228.0, step = 49

In [23]:
#Evaluate the testing dataset
model.evaluate(input_fn=input_test_func)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-05-30-19:57:02
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/js/vq_cts194qscfxyy3tzq_lg80000gn/T/tmpqgoBs8/model.ckpt-50000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-05-30-19:57:02
INFO:tensorflow:Saving dict for global step 50000: average_loss = 51363824.0, global_step = 50000, loss = 503616030.0


{'average_loss': 51363824.0, 'global_step': 50000, 'loss': 503616030.0}