In [15]:
#Relevant imports

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Basics

In [16]:
#Operations on Constants

fname = tf.constant("Inderpreet")
lname = tf.constant(" Singh")
name = fname + lname

num1 = tf.constant(1)
num2 = tf.constant(2)
num3 = num1 + num2

with tf.Session() as sess:
    name = sess.run(name)
    num = sess.run(num3)
    
print(name)
print(num)

Inderpreet Singh
3


In [17]:
#Pipeline of Operations

const = tf.constant(10.0)
ones = tf.ones(shape=[2,2])
zeros = tf.zeros(shape=[2,2])
fillmat = tf.fill([2,2],10)
randuni = tf.random_uniform([2,2],minval=0,maxval=10)
randnorm = tf.random_normal([2,2],mean=10,stddev=2)

list_operations = [const, ones, zeros, fillmat, randuni, randnorm]

with tf.Session() as sess:
    for op in list_operations:
        print("\n")
        print(sess.run(op))
    



10.0


[[1. 1.]
 [1. 1.]]


[[0. 0.]
 [0. 0.]]


[[10 10]
 [10 10]]


[[5.32506   5.1838064]
 [5.332606  2.6822257]]


[[ 7.200223  10.6243   ]
 [ 9.02965    7.9038057]]


In [18]:
#Matrix Multiplication

mat1 = tf.constant([[1,1],[2,3]])
mat2 = tf.constant([[1],[1]])
mat3 = tf.matmul(mat1,mat2)

with tf.Session() as sess:
    print(sess.run(mat3))

[[2]
 [5]]


In [21]:
#Variables

randn = tf.random_normal([2,2],mean=10,stddev=2)
var1 = tf.Variable(initial_value=randn)
var2 = tf.Variable(1.0)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(var1))
    print("\n")
    print(sess.run(var2))
    
    

[[ 9.511304  8.711362]
 [11.350275  8.962854]]


1.0


In [22]:
#Placeholders

ph1 = tf.placeholder(tf.float32, shape=[None,5])
ph2 = tf.placeholder(tf.float32)

# Graphs

In [23]:
print(tf.get_default_graph)
graph = tf.Graph()
print(graph)

<function get_default_graph at 0x118200de8>


In [24]:
graph1 = tf.get_default_graph()
graph2 = tf.Graph()

graph1 is tf.get_default_graph()

True

In [25]:
graph2 is tf.get_default_graph()

False

In [27]:
with graph2.as_default():
    print(graph2 is tf.get_default_graph())

True
